GET http://localhost:5182/games

###

GET http://localhost:5182/games/22

###

POST http://localhost:5182/games
Content-Type: application/json

{
    "name": "Street Fighter II",
    "genreId": 4,
    "price": 35.99,
    "releaseDate": "2022-03-20"
}

###

PUT http://localhost:5182/games/22
Content-Type: application/json

{
    "name": "Street Fight reloaded",
    "genre": "Fighting",
    "price": 79.99,
    "releaseDate": "1996-07-22"
}

###

DELETE http://localhost:5182/games/2

###

GET http://localhost:5182/genres
